version: 0.0.{build}
image: Visual Studio 2017
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
build_script:
- cmd: msbuild .\SCurry.sln /v:m /m /t:Restore,Build,Pack /p:Configuration=Release
deploy_script:
- cmd: nuget push .\scurry\bin\Release\SCurry.{version}.nupkg -ApiKey RyXKOJamWIT+EDXvkiJFDp6dY4kbgzpjvLRXVrWBwgo= -Source https://ci.appveyor.com/nuget/sgaliamov/api/v2/package