version: 0.1.{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  Configuration: Release
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
- pwsh: msbuild .\SCurry.sln /v:m /m /t:Restore

build:
  project: SCurry.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

before_test:
- pwsh: |
    nuget install OpenCover -Verbosity quiet -Version 4.6.519

test_script:
- pwsh: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Get-ChildItem .\**\*.Tests.csproj -Recurse | % {
        .\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test $_" -output:".\obj\$($_.Name).coverage.xml" -oldstyle
    }
    Get-ChildItem .\obj\ -include *.coverage.xml -rec | % { gc $_ } | out-file .\coverage.xml
    bash .build\codecov.sh -f "coverage.xml" -t $env:OpenCoverToken

#artifacts:
#- path: .\SCurry\bin\Release\**\*.nupkg
#  name: appveyor-nuget

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master