version: 0.1.{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  Configuration: Release
  OpenCoverVersion: 4.6.519
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
- pwsh: msbuild .\SCurry.sln /v:m /m /t:Restore

build:
  project: SCurry.sln
  parallel: true
  verbosity: minimal

before_test:
- pwsh: nuget install OpenCover -Verbosity quiet -Version $env:OpenCoverVersion

test_script:
- .\build\run-tests.ps1
    

#artifacts:
#- path: .\SCurry\bin\Release\**\*.nupkg
#  name: appveyor-nuget

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master