version: 0.1.{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  Configuration: Release
  OpenCoverVersion: 4.6.519
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
- pwsh: msbuild .\SCurry.sln /v:m /m /t:Restore

build:
  project: SCurry.sln
  parallel: true
  verbosity: minimal

before_test:
- pwsh: nuget install OpenCover -Verbosity quiet -Version $env:OpenCoverVersion

test_script:
- pwsh: |
    Write-Information "Testing..."
    New-Item -ItemType "directory" -Name "coverage"
    Get-ChildItem .\**\*.Tests.csproj -Recurse | ForEach-Object {
        .\OpenCover.$($env:OpenCoverVersion)\tools\OpenCover.Console.exe `
            -register:user `
            -target:"C:\Program Files\dotnet\dotnet.exe" `
            -targetargs:"test $_" `
            -output:".\coverage\$($_.Name).coverage.xml" `
            -oldstyle
    }
    Get-ChildItem .\coverage\ -include *.coverage.xml -Recurse | ForEach-Object { Get-Content $_ } | Out-File .\coverage.xml
    Write-Host "Publish test coverage..." -ForegroundColor Green
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    bash .build\codecov.sh -f "coverage.xml" -t $env:OpenCoverToken

#artifacts:
#- path: .\SCurry\bin\Release\**\*.nupkg
#  name: appveyor-nuget

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master