version: build.{build}

branches:
  only:
    - master

skip_branch_with_pr: true

image: Visual Studio 2019

environment:
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

configuration: Release

init:
- pwsh: $env:PATH = "C:\msys64\usr\bin;" + $env:PATH

before_build:
- pwsh: gitversion /l console /output buildserver /verbosity warn

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_MajorMinorPatch)
  file_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_InformationalVersion)

build_script:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
        $env:CONFIGURATION = "debug"
    }
    .\scripts\build.ps1 -c $env:CONFIGURATION

before_test:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "develop") {
        nuget install OpenCover -Verbosity quiet -Version 4.6.519
    }

test_script:
- pwsh: .\scripts\test_script.ps1

before_deploy:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
      dotnet pack --include-source --include-symbols --no-build --no-dependencies
    }

artifacts:
- path: '.\publish\*.nupkg'
  name: nuget-package
  type: NuGetPackage

deploy:
# - provider: Environment
#   name: appveyor-nuget
#   on:
#     branch: master
- provider: Environment
  name: appveyor-nuget
  on:
    APPVEYOR_REPO_TAG: true
