version: 0.0.{build}
image: Visual Studio 2017
clone_depth: 1
dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
build_script:
- cmd: msbuild .\SCurry.sln /v:m /m /t:Restore,Build,Pack /p:Configuration=Release
test_script:
- pwsh: Get-ChildItem .\**\*.Tests.dll -Recurse | % { xunit.console $_.FullName /appveyor }
artifacts:
- path: '**\*.nupkg'
  name: appveyor-nugen
deploy:
- provider: Environment
  name: appveyor-nuget