version: 0.1.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2017
clone_depth: 1
dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
build_script:
- pwsh: msbuild .\SCurry.sln /v:m /m /t:Restore,Build,Pack /p:Configuration=Release
test_script:
- pwsh: Get-ChildItem .\**\*.Tests.csproj -Recurse | % { dotnet test $_.FullName }
environment:
  YourUploadToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni
test_script:
- pwsh: |
    $items = @(Get-ChildItem .\**\*.Tests.dll -Recurse | % { $_.FullName })
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"xunit.console" -targetargs:"$items -noshadow" -output:"coverage.xml"
after_test:
- pwsh: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "coverage.xml" -t $env:YourUploadToken

artifacts:
- path: '**\*.nupkg'
deploy:
- provider: Environment
  name: appveyor-nuget