version: 0.3.{build}

branches:
  only:
    - master
    - develop

skip_tags: true

skip_branch_with_pr: true

image: Visual Studio 2017

clone_depth: 1

environment:
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

init:
- pwsh: $env:PATH = "C:\msys64\usr\bin;" + $env:PATH

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

configuration: Release

before_build:
- pwsh: dotnet restore --verbosity q

build:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        .\build.ps1 $env:CONFIGURATION
    } else {
        .\build.ps1 Debug
    }

before_test:
- pwsh: nuget install OpenCover -Verbosity quiet -Version 4.6.519

test_script:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "develop") {
        Get-ChildItem .\**\*.Tests.csproj -Recurse | % {
            .\OpenCover.4.6.519\tools\OpenCover.Console.exe `
                -register:user `
                -target:"C:\Program Files\dotnet\dotnet.exe" `
                -targetargs:"test $_ --no-build" `
                -output:"coverage.xml" `
                -oldstyle
            bash .appveyor\codecov.sh -f "coverage.xml" -t $env:OpenCoverToken
        }
    }

before_deploy:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        dotnet pack .\SCurry\ --include-source --include-symbols --no-build --no-dependencies
        Get-ChildItem ".\SCurry\**\*.nupkg" -Recurse | % {
            Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName "appveyor-nuget"
        }
    }

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master
