version: 0.0.{build}
image: Visual Studio 2017
clone_depth: 1
dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
build_script:
- cmd: msbuild .\SCurry.sln /v:m /m /t:Restore,Build,Pack /p:Configuration=Release
test:
  assemblies:
    only:
    - '**\*.Tests.dll'
environment:
  ApiKey:
    secure: RyXKOJamWIT+EDXvkiJFDp6dY4kbgzpjvLRXVrWBwgo=
deploy_script:
- cmd: nuget push .\scurry\bin\Release\SCurry.*.nupkg -ApiKey {ApiKey} -Source https://ci.appveyor.com/nuget/sgaliamov/api/v2/package