version: 0.0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    msbuild .\SCurry.Builders.sln /v:m /m /t:Restore,Build

    msbuild .\SCurry.sln /v:m /m /t:Restore,TransformAll,Build
