version: 1.1.{build}

branches:
  only:
    - master
    - develop

skip_tags: true

skip_branch_with_pr: true

image: Visual Studio 2017

clone_depth: 1

environment:
  OpenCoverToken:
    secure: rJrOmfdpmHx8EdfB7nBpijgy1H9vGRXi8jARISWwUrXeZGxTiEnHmr1c2e6BARni

init:
- pwsh: $env:PATH = "C:\msys64\usr\bin;" + $env:PATH

dotnet_csproj:
  patch: true
  file: SCurry\SCurry.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

configuration: Release

build_script:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
        $env:CONFIGURATION = "debug"
    }
    .\build.ps1 -c $env:CONFIGURATION

before_test:
- pwsh: |
    if ($env:APPVEYOR_REPO_BRANCH -eq "develop") {
        nuget install OpenCover -Verbosity quiet -Version 4.6.519
    }

test_script:
- pwsh: .\.appveyor\test_script.ps1

before_deploy:
- pwsh: .\.appveyor\before_deploy.ps1

deploy:
- provider: Environment
  name: appveyor-nuget
  on:
    branch: master
